%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.13.0

-ifndef(test_pb).
-define(test_pb, true).

-define(test_pb_gpb_version, "4.13.0").

-ifndef('TEST_PB_PB_H').
-define('TEST_PB_PB_H', true).
-record(test_pb,
        {id = 0                 :: non_neg_integer() | undefined % = 1, 64 bits
        }).
-endif.

-endif.
